version: '3.8'

services:
  client-backend:
    image: client:0.0.1
    container_name: 'coffee_order_system_backend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - service-db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/coffee_order_system'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=root'
    volumes:
      - ./docker-compose-data/logs:/app/logs

  service-db:
    image: 'postgres:13'
    container_name: 'coffee_order_system_db'
    ports:
      - '5050:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=coffee_order_system'
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./docker-compose-data/db-data:/var/lib/postgresql/data